# Generated by Django 2.2.16 on 2020-11-01 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(default=datetime.datetime(2020, 11, 1, 14, 38, 3, 572293, tzinfo=utc))),
                ('statement_description', models.CharField(max_length=128)),
                ('statement_income', models.DecimalField(decimal_places=2, max_digits=7)),
                ('statement_expense', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
